### ISSUE TITLE
Metadata information for platform/monitored resources not populated by default for GKE container projects

### ISSUE THREAD

**Issue by tillig** [googleapis/gax-dotnet#276]
.NET applications running inside containers in Google Kubernetes Engine pods don't correctly populate the data for "pod ID" and "namespace ID" by default due to permissions on the Kubernetes API.

This is a challenge when using the ASP.NET Core integration with Stackdriver because the log entries don't get attributed to the right namespace and pod - queries don't work.

The ASP.NET Core integration [uses `MonitoredResourceBuilder.FromPlatform()` to populate the metadata for log entries](https://github.com/GoogleCloudPlatform/google-cloud-dotnet/blob/master/apis/Google.Cloud.Diagnostics.AspNetCore/Google.Cloud.Diagnostics.AspNetCore/Logging/LoggerOptions.cs#L87).

The `MonitoredResourceBuilder.FromPlatform()` uses the current environment to get information about the platform. This happens in `Google.Api.Gax.Platform.LoadInstanceAsync()` and there's a [specific section for handling GKE info](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L603).

When the GKE info is loaded, it [gets the pod name from the environment variable `HOSTNAME`](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L233) and the [namespace name from a mounted file in the filesystem](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L247). The pod and namespace are needed to read additional information [from the Kubernetes API](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L285). The important part here is **at this point the values are known**.

When creating the master set of `GkePlatformDetails`, these values get ignored [in favor of parsing the data from JSON retrieved from the Kubernetes API](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L368-L369). This is a challenge because [if there's a problem reading from the Kubernetes API then no JSON is retrieved and, thus, can't be parsed](https://github.com/googleapis/gax-dotnet/blob/master/Google.Api.Gax/Platform.cs#L293).

By default, the service account running pod containers, at least when deployed into a namespace (i.e., not the default namespace and not the service account in the default namespace) **doesn't appear to have read access to the Kubernetes API.** The result of this is that the read into the Kubernetes API returns a 403, no JSON is set, no pod/namespace data can be parsed, and log information ends up being attributed to the default namespace with no pod ID.

The workaround is to grant the default service account in your namespace `get` access on `pods` and `namespaces` for the namespace.

You need a role for the namespace...

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: your-namespace
  name: metadata-reader
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get"]
```

...and a role binding for the default service account in the namespace...

```yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metadata-reader
  namespace: your-namespace
subjects:
- kind: ServiceAccount
  name: default
  namespace: your-namespace
roleRef:
  kind: Role
  name: metadata-reader
  apiGroup: rbac.authorization.k8s.io
```

The workaround could be avoided if the pod and namespace data was retained rather than ignored and reparsed.

**Comment by jskeet** [comment]
Thanks for the detailed issue report. I wonder if the default access to the Kubernetes API has changed since the code was written - that wouldn't entirely surprise me.

cc @chrisdunelm in case he remembers anything more that would help Amanda investigate.

**Comment by chrisdunelm** [comment]
I don't recall any issues with the API permissions when this was originally implemented. However, it's possible I was using an account which had this permission and incorrectly assumed that the permission was allowed by default.
Agreed that the ignoring/reparsing of data seems broken, and should be fixed.

**Comment by tillig** [comment]
Something I'm looking at is the possibility of a convention-driven use of the [downward API](https://kubernetes.io/docs/tasks/inject-data-application/downward-api-volume-expose-pod-information/) to put stuff in well-known locations either as files or environment variables, similar to the way the logic currently knows to retrieve the service account data from a known file location. Not sure if that's something interesting to provide as a fallback or not. Seems there are already several `KUBERNETES_*` environment variables. Perhaps folks could opt-in to putting things in a convention-based location rather than requiring the API calls?

**Comment by amanda-tarafa** [comment]
That's interesting, I'm not sure we would like to include this as a fallback on the client library but it's definitely an alternative for code that doesn't want to rely on the API calls. I'll check with the team, I'm not personally a fan of adding too many conventions at a client library level tbh.

And I'm looking at the original issue now.

**Comment by tillig** [comment]
That's fair. I just happened to be adding other things (labels, metadata, pod info) for enhanced logging and thought it might be an idea.

For folks interested, here is a snippet gleaned from the k8s docs showing how to get the metadata into the environment. Note labels and annotations are only available as volume mounts.

```yaml
apiVersion: apps/v1beta2
kind: Deployment
spec:
  template:
    spec:
      containers:
        - name: namehere
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBERNETES_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KUBERNETES_POD_UID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
            - name: KUBERNETES_SERVICEACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
```

I'm following a similar convention to the other environment variables that just show up, like `KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT`. The `KUBERNETES_POD_NAME` added via yaml and the `HOSTNAME` variable added by the system look like they'll always be the same, though I'm not sure if that's guaranteed.
